CREATE TABLE "ADMIN"."CONDOMINIOS" 
   (	"ID_CONDOMINIO" NUMBER, 
	"CNPJ" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CEP" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LOGRADOURO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMERO" NUMBER, 
	"BAIRRO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CIDADE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ESTADO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "ADMIN"."CONDOMINIOS_PK" ON "ADMIN"."CONDOMINIOS" ("ID_CONDOMINIO") 
  ;

ALTER TABLE "ADMIN"."CONDOMINIOS" ADD CONSTRAINT "CONDOMINIOS_PK" PRIMARY KEY ("ID_CONDOMINIO")
  USING INDEX  ENABLE;

