CREATE TABLE "ADMIN"."SENSORES" 
   (	"ID_SENSOR" NUMBER, 
	"ID_CONDOMINIO" NUMBER, 
	"AREA" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ANDAR" NUMBER, 
	"UNIDADE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "ADMIN"."UNDEFINED_PK" ON "ADMIN"."SENSORES" ("ID_SENSOR") 
  ;

ALTER TABLE "ADMIN"."SENSORES" ADD CONSTRAINT "UNDEFINED_PK" PRIMARY KEY ("ID_SENSOR")
  USING INDEX  ENABLE;

