CREATE TABLE "ADMIN"."MONITORAMENTO" 
   (	"ID_SENSOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"INTENSIDADE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

